`define MPU_PRESENT 1
`define LVL_WIDTH 3
`define WIC_PRESENT 1
`define WIC_LINES 3
`define BB_PRESENT 1
`define DEBUG_LVL 3
`define TRACE_LVL 1
`define JTAG_PRESENT 1
`define ROM_SIZE 4'b0011
`define ROM_INIT_PATH "F:/EMB_pub/embedded/cortex_m3/ref_design/1.0.1/fpga_ref_design/DK_START_GW2A55_V1.3/gowin_empu_m3/bootloader/INSMEM_Size_64KB"
`define RAM_SIZE 4'b0011
